name = "packwiz-test"
author = "moumse"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ff9a654b2f2811bdbe7af9679b3b900ddd895e7c02714726c05d43a1fc8dce7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
unsup = "1.3-snap.260+2199fa37d8"
