[blocks]
	"Pottery Table" = true
	Kiln = false
	"Chiseled bricks" = true
	"Glazed terracotta" = true
	Concrete = false
	"Terracotta slabs, stairs, and walls" = false
	"Terracotta bricks" = true
	"Glass doors" = true

	[blocks.decorated_pot]
		"Decorated pot colors" = true
		"Decorated pot trims" = true
