#.
#Migrate copycats to Create: Copycats+ when they receive a block update
migrateCopycatsOnBlockUpdate = true
#.
#Migrate copycats to Create: Copycats+ when their block entities are initialized
migrateCopycatsOnInitialize = true

#.
#Enable/disable features. Values on server override clients
[features]
	#.
	kinetic_bridge = true
	item_silo = true
	empty_fan_catalyst = true
	red_fluid_vessel = true
	lime_fluid_vessel = true
	verdant_fluid_vessel = true
	kinetic_battery = true
	orange_fluid_vessel = true
	mint_fluid_vessel = true
	light_gray_fluid_vessel = true
	brass_chute = true
	brake = true
	copycat_fence_gate = true
	white_fluid_vessel = true
	navy_fluid_vessel = true
	copycat_stairs = true
	tan_fluid_vessel = true
	brass_gearbox = true
	copycat_vertical_step = true
	copycat_wall = true
	six_way_gearbox = true
	crank_wheel = true
	aqua_fluid_vessel = true
	encased_chain_cogwheel = true
	dashboard = true
	shear_pin = true
	pink_fluid_vessel = true
	teal_fluid_vessel = true
	inverted_gearshift = true
	slate_fluid_vessel = true
	forest_fluid_vessel = true
	copycat_board = true
	inventory_bridge = true
	copycat_fence = true
	olive_fluid_vessel = true
	fluid_vessel = true
	cross_connector = true
	green_fluid_vessel = true
	beige_fluid_vessel = true
	ginger_fluid_vessel = true
	inverted_clutch = true
	parallel_gearbox = true
	redstone_link_wildcard = true
	black_fluid_vessel = true
	cyan_fluid_vessel = true
	inventory_access_port = true
	centrifugal_clutch = true
	copycat_slab = true
	yellow_fluid_vessel = true
	blue_fluid_vessel = true
	overstress_clutch = true
	copycat_block = true
	purple_fluid_vessel = true
	magenta_fluid_vessel = true
	rose_fluid_vessel = true
	large_crank_wheel = true
	gray_fluid_vessel = true
	amber_fluid_vessel = true
	light_blue_fluid_vessel = true
	indigo_fluid_vessel = true
	brown_fluid_vessel = true
	sequenced_pulse_generator = true
	freewheel_clutch = true
	maroon_fluid_vessel = true
	linked_transmitter = true
	coral_fluid_vessel = true
	copycat_beam = true

#.
#Enable/disable categories of features. Disabling a category hides all related features. Values on server override clients
[feature_categories]
	#.
	#.
	#All kinetic components, such as gearboxes and crank wheels
	kinetic = true
	#.
	#All redstone components, such as linked transmitter and sequenced pulse generator
	redstone = true
	#.
	#All components related to item and fluid transport
	logistics = true
	#.
	#All copycats (Install Create: Copycats+ to upgrade)
	copycats = true
	#.
	#All building palette blocks
	palette = true
