#Which mode to use for rendering clouds.
#
#SHADER: Use the original mod's shaders (no change to cloud rendering)
#CLASSIC: Use this mod's particle rendering system
#DISABLE: Disable all cloud rendering
#Allowed Values: SHADER, CLASSIC, DISABLE
render_mode = "SHADER"
#Enables/disables mist particles in heavy rain
enable_mist = true
#Enables/disables rain splash particles
enable_splash = true
#Enables more intense fog/darkness effects for precipitation. Does nothing on SHADER rendering mode
enhanced_fog = true
#Rate at which storms and cloud map are updated
# Default: 200
# Range: 40 ~ 400
update_every_ticks = 200
#Crossover ticks for particle fade/switchover. Should only need modified if using a resource pack
# Default: 60
# Range: 1 ~ 100
particle_crossover = 60
#Fixes bleeding issues on SHADER rendering mode. Disables shader culling (major performance hit! may be reworked in the future...)
#
#FULL: Disables all culling, biggest performance hit
#LIGHT: Keeps solid block culling, only fixes bleeding around small blocks/entities/beacons/etc.
#DISABLE: No changes to PMW culling behavior
#Allowed Values: FULL, LIGHT, DISABLE
bleed_fix_mode = "FULL"
