[common]
	#Displays precise information about track blocks, curves, and track placement.
	precise_overlay = true
	#Disables hitbox(outline) of track curves.
	no_track_overlay = false

[compat]
	#(Experimental) For Pantographs and Wires mod, add feature to adjust cantileverwidth/yOffset consistently.
	pantographs_and_wires__auto_cantilever = false

[flexi_trak]
	#Specify how wide placement overlays are shown.
	# Default: 3
	# Range: 0 ~ 7
	overlay_width = 3
	#Whether hold or toggle to enable/disable flexible placement.
	#Allowed Values: Hold, Toggle
	flexible_selection = "Hold"
